// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_FINAL_H
#define UI_FINAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_final
extern void ui_final_screen_init(void);
extern void ui_final_screen_destroy(void);
extern void ui_event_final(lv_event_t * e);
extern lv_obj_t * ui_final;
extern lv_obj_t * ui_image_printer;
extern void ui_event_Button4_Button(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_label_ready;
extern lv_obj_t * ui_ok_group;
extern lv_obj_t * ui_image_ok_big;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

