// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#include "../ui.h"

lv_obj_t * ui_final = NULL;
lv_obj_t * ui_image_printer = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_label_ready = NULL;
lv_obj_t * ui_ok_group = NULL;
lv_obj_t * ui_image_ok_big = NULL;
// event funtions
void ui_event_final(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        topon_Animation(ui_label_ready, 0);
        lefton_Animation(ui_image_ok_big, 200);
        opaon_Animation(ui_image_printer, 100);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        topoff_Animation(ui_label_ready, 0);
        leftoff_Animation(ui_image_ok_big, 100);
        opaoff_Animation(ui_image_printer, 200);
    }
}

void ui_event_Button4_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main_menu, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_main_menu_screen_init);
    }
}

// build funtions

void ui_final_screen_init(void)
{
    ui_final = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_final, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_final, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_final, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_final, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_final, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_final, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_final, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_final, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_printer = lv_image_create(ui_final);
    lv_image_set_src(ui_image_printer, &ui_img_print_ready_png);
    lv_obj_set_width(ui_image_printer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_printer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_printer, 0);
    lv_obj_set_y(ui_image_printer, -15);
    lv_obj_set_align(ui_image_printer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_printer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image_printer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = ui_Button_create(ui_final);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 0);

    lv_label_set_text(ui_comp_get_child(ui_Button4, UI_COMP_BUTTON_LABEL_BUTTON), "Ready");

    ui_label_ready = lv_label_create(ui_final);
    lv_obj_set_width(ui_label_ready, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ready, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_ready, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_ready, "Ready to print");
    lv_obj_set_style_text_color(ui_label_ready, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_ready, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_ready, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ok_group = lv_obj_create(ui_final);
    lv_obj_set_width(ui_ok_group, 394);
    lv_obj_set_height(ui_ok_group, 335);
    lv_obj_set_x(ui_ok_group, -100);
    lv_obj_set_y(ui_ok_group, 0);
    lv_obj_set_align(ui_ok_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ok_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ok_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ok_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_ok_big = lv_image_create(ui_ok_group);
    lv_image_set_src(ui_image_ok_big, &ui_img_ok_big_png);
    lv_obj_set_width(ui_image_ok_big, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_ok_big, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_image_ok_big, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image_ok_big, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_image_ok_big, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_final, ui_event_final, LV_EVENT_ALL, NULL);

}

void ui_final_screen_destroy(void)
{
    if(ui_final) lv_obj_del(ui_final);

    // NULL screen variables
    ui_final = NULL;
    ui_image_printer = NULL;
    ui_Button4 = NULL;
    ui_label_ready = NULL;
    ui_ok_group = NULL;
    ui_image_ok_big = NULL;

}
