// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_MAIN_MENU_H
#define UI_MAIN_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main_menu
extern void ui_main_menu_screen_init(void);
extern void ui_main_menu_screen_destroy(void);
extern void ui_event_main_menu(lv_event_t * e);
extern lv_obj_t * ui_main_menu;
extern lv_obj_t * ui_header_group3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_pos_group;
extern lv_obj_t * ui_posx;
extern lv_obj_t * ui_label_x;
extern lv_obj_t * ui_label_x1;
extern lv_obj_t * ui_posy;
extern lv_obj_t * ui_label_y;
extern lv_obj_t * ui_label_y2;
extern lv_obj_t * ui_posz;
extern lv_obj_t * ui_label_z1;
extern lv_obj_t * ui_label_z2;
extern lv_obj_t * ui_content_group3;
extern void ui_event_button_menu_print_button_menu(lv_event_t * e);
extern lv_obj_t * ui_button_menu_print;
extern void ui_event_button_menu_settings_button_menu(lv_event_t * e);
extern lv_obj_t * ui_button_menu_settings;
extern void ui_event_button_control_control_button_menu(lv_event_t * e);
extern lv_obj_t * ui_button_control_control;
extern lv_obj_t * ui_footer_group3;
extern lv_obj_t * ui_text_bg_group3;
extern lv_obj_t * ui_text_bg_group2;
extern lv_obj_t * ui_text_bg_group4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

