// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_PRINTING_H
#define UI_PRINTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_printing
extern void ui_printing_screen_init(void);
extern void ui_printing_screen_destroy(void);
extern void ui_event_printing(lv_event_t * e);
extern lv_obj_t * ui_printing;
extern lv_obj_t * ui_header_group4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_pos_group1;
extern lv_obj_t * ui_posx1;
extern lv_obj_t * ui_label_x2;
extern lv_obj_t * ui_label_x3;
extern lv_obj_t * ui_posy1;
extern lv_obj_t * ui_label_y1;
extern lv_obj_t * ui_label_y3;
extern lv_obj_t * ui_posz1;
extern lv_obj_t * ui_label_z3;
extern lv_obj_t * ui_label_z4;
extern lv_obj_t * ui_content_group4;
extern lv_obj_t * ui_print_preview;
extern lv_obj_t * ui_separetor_left;
extern lv_obj_t * ui_separator_right;
extern lv_obj_t * ui_printing_percent_group;
extern lv_obj_t * ui_printing_percent;
extern lv_obj_t * ui_printing_percent1;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_temp_group;
extern lv_obj_t * ui_bar_group;
extern lv_obj_t * ui_bar_group1;
extern lv_obj_t * ui_printing_group;
extern lv_obj_t * ui_printing_btn_group;
extern lv_obj_t * ui_button_print;
extern void ui_event_button_print1_button_print(lv_event_t * e);
extern lv_obj_t * ui_button_print1;
extern lv_obj_t * ui_printing_params_group;
extern lv_obj_t * ui_text_bg_group6;
extern lv_obj_t * ui_text_bg_group5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

