// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_STEP1_H
#define UI_STEP1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_step1
extern void ui_step1_screen_init(void);
extern void ui_step1_screen_destroy(void);
extern void ui_event_step1(lv_event_t * e);
extern lv_obj_t * ui_step1;
extern lv_obj_t * ui_header_group;
extern lv_obj_t * ui_wizard_group;
extern lv_obj_t * ui_dot1;
extern lv_obj_t * ui_line1;
extern lv_obj_t * ui_dot2;
extern lv_obj_t * ui_line2;
extern lv_obj_t * ui_dot3;
extern lv_obj_t * ui_content_group;
extern lv_obj_t * ui_content_text_group;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_content_temp_group;
extern lv_obj_t * ui_text_bg_group;
extern lv_obj_t * ui_text_bg_group1;
extern lv_obj_t * ui_separator;
extern lv_obj_t * ui_footer_group;
extern void ui_event_Button_Button(lv_event_t * e);
extern lv_obj_t * ui_Button;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

