// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_STEP2_H
#define UI_STEP2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_step2
extern void ui_step2_screen_init(void);
extern void ui_step2_screen_destroy(void);
extern void ui_event_step2(lv_event_t * e);
extern lv_obj_t * ui_step2;
extern lv_obj_t * ui_step2_bg;
extern lv_obj_t * ui_bed;
extern lv_obj_t * ui_nozzle;
extern lv_obj_t * ui_header_group1;
extern lv_obj_t * ui_wizard_group1;
extern lv_obj_t * ui_dot4;
extern lv_obj_t * ui_line3;
extern lv_obj_t * ui_dot5;
extern lv_obj_t * ui_line4;
extern lv_obj_t * ui_dot6;
extern lv_obj_t * ui_content_group1;
extern lv_obj_t * ui_content_text_group1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_label_calibration;
extern lv_obj_t * ui_footer_group1;
extern void ui_event_Button1_Button(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

