// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_settings_bg;
extern lv_obj_t * ui_header_group6;
extern lv_obj_t * ui_settings_label;
extern void ui_event_back_button(lv_event_t * e);
extern lv_obj_t * ui_back_button;
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_content_group6;
extern lv_obj_t * ui_content_text_group4;
extern lv_obj_t * ui_list;
extern lv_obj_t * ui_list1;
extern lv_obj_t * ui_list2;
extern lv_obj_t * ui_list3;
extern lv_obj_t * ui_list4;
extern lv_obj_t * ui_list5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

