// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#include "../ui.h"

lv_obj_t * ui_step2 = NULL;
lv_obj_t * ui_step2_bg = NULL;
lv_obj_t * ui_bed = NULL;
lv_obj_t * ui_nozzle = NULL;
lv_obj_t * ui_header_group1 = NULL;
lv_obj_t * ui_wizard_group1 = NULL;
lv_obj_t * ui_dot4 = NULL;
lv_obj_t * ui_line3 = NULL;
lv_obj_t * ui_dot5 = NULL;
lv_obj_t * ui_line4 = NULL;
lv_obj_t * ui_dot6 = NULL;
lv_obj_t * ui_content_group1 = NULL;
lv_obj_t * ui_content_text_group1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_label_calibration = NULL;
lv_obj_t * ui_footer_group1 = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_step2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        topon_Animation(ui_wizard_group1, 0);
        lefton_Animation(ui_content_text_group1, 100);
        opaon_Animation(ui_step2_bg, 200);
        topon_Animation(ui_label_calibration, 300);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        topoff_Animation(ui_wizard_group1, 0);
        leftoff_Animation(ui_content_text_group1, 100);
        opaoff_Animation(ui_step2_bg, 0);
        topoff_Animation(ui_label_calibration, 100);
    }
}

void ui_event_Button1_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_step3, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_step3_screen_init);
    }
}

// build funtions

void ui_step2_screen_init(void)
{
    ui_step2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_step2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_step2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_step2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_step2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_step2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_step2, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_step2_bg = lv_image_create(ui_step2);
    lv_image_set_src(ui_step2_bg, &ui_img_step2_bg_png);
    lv_obj_set_width(ui_step2_bg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_step2_bg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_step2_bg, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_step2_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_step2_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bed = lv_image_create(ui_step2_bg);
    lv_image_set_src(ui_bed, &ui_img_bed_png);
    lv_obj_set_width(ui_bed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bed, 30);
    lv_obj_set_y(ui_bed, 229);
    lv_obj_set_align(ui_bed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nozzle = lv_image_create(ui_step2_bg);
    lv_image_set_src(ui_nozzle, &ui_img_nozzle_png);
    lv_obj_set_width(ui_nozzle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nozzle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nozzle, 151);
    lv_obj_set_y(ui_nozzle, 166);
    lv_obj_set_align(ui_nozzle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nozzle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_nozzle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header_group1 = lv_obj_create(ui_step2);
    lv_obj_set_height(ui_header_group1, 130);
    lv_obj_set_width(ui_header_group1, lv_pct(100));
    lv_obj_set_align(ui_header_group1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_header_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_header_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wizard_group1 = lv_obj_create(ui_header_group1);
    lv_obj_set_width(ui_wizard_group1, 414);
    lv_obj_set_height(ui_wizard_group1, 50);
    lv_obj_set_align(ui_wizard_group1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wizard_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wizard_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wizard_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wizard_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wizard_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_wizard_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_wizard_group1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4 = ui_dot_create(ui_wizard_group1);
    lv_obj_set_x(ui_dot4, 0);
    lv_obj_set_y(ui_dot4, 0);
    lv_obj_remove_state(ui_dot4, LV_STATE_CHECKED);     /// States

    lv_obj_remove_flag(ui_comp_get_child(ui_dot4, UI_COMP_DOT_READY_BG), LV_OBJ_FLAG_HIDDEN);      /// Flags

    lv_obj_remove_flag(ui_comp_get_child(ui_dot4, UI_COMP_DOT_READY), LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_line3 = lv_obj_create(ui_wizard_group1);
    lv_obj_set_width(ui_line3, 100);
    lv_obj_set_height(ui_line3, 3);
    lv_obj_set_align(ui_line3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_line3, LV_STATE_CHECKED);       /// States
    lv_obj_remove_flag(ui_line3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_line3, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line3, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_line3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_dot5 = ui_dot_create(ui_wizard_group1);
    lv_obj_set_x(ui_dot5, 0);
    lv_obj_set_y(ui_dot5, 0);
    lv_obj_add_state(ui_dot5, LV_STATE_CHECKED);       /// States

    lv_label_set_text(ui_comp_get_child(ui_dot5, UI_COMP_DOT_LABEL_DOT), "2");

    ui_line4 = lv_obj_create(ui_wizard_group1);
    lv_obj_set_width(ui_line4, 100);
    lv_obj_set_height(ui_line4, 3);
    lv_obj_set_align(ui_line4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_line4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_line4, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line4, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_line4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_dot6 = ui_dot_create(ui_wizard_group1);
    lv_obj_set_x(ui_dot6, 0);
    lv_obj_set_y(ui_dot6, 0);

    lv_label_set_text(ui_comp_get_child(ui_dot6, UI_COMP_DOT_LABEL_DOT), "3");

    ui_content_group1 = lv_obj_create(ui_step2);
    lv_obj_set_width(ui_content_group1, lv_pct(100));
    lv_obj_set_flex_grow(ui_content_group1, 1);
    lv_obj_set_align(ui_content_group1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_content_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_group1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_text_group1 = lv_obj_create(ui_content_group1);
    lv_obj_set_width(ui_content_text_group1, lv_pct(62));
    lv_obj_set_height(ui_content_text_group1, lv_pct(100));
    lv_obj_set_align(ui_content_text_group1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_content_text_group1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_text_group1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_text_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_text_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_text_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_text_group1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_text_group1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_text_group1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_text_group1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_text_group1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_text_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_content_text_group1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label3, "Calibrating");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_content_text_group1);
    lv_obj_set_width(ui_Label4, lv_pct(103));
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label4,
                      "The printer automatically calibrates the distance between the head and the bed. After calibration, you no longer need to adjust it manually.");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_calibration = lv_label_create(ui_content_group1);
    lv_obj_set_width(ui_label_calibration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_calibration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_calibration, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_calibration, "The calibration is complete");
    lv_obj_add_state(ui_label_calibration, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_label_calibration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_calibration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_calibration, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_label_calibration, 50, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_label_calibration, lv_color_hex(0x49AD46), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_label_calibration, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_label_calibration, 22, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_label_calibration, 22, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_label_calibration, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_label_calibration, 8, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_footer_group1 = lv_obj_create(ui_step2);
    lv_obj_set_height(ui_footer_group1, 138);
    lv_obj_set_width(ui_footer_group1, lv_pct(100));
    lv_obj_set_align(ui_footer_group1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_footer_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_footer_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = ui_Button_create(ui_footer_group1);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 0);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_step2, ui_event_step2, LV_EVENT_ALL, NULL);

}

void ui_step2_screen_destroy(void)
{
    if(ui_step2) lv_obj_del(ui_step2);

    // NULL screen variables
    ui_step2 = NULL;
    ui_step2_bg = NULL;
    ui_bed = NULL;
    ui_nozzle = NULL;
    ui_header_group1 = NULL;
    ui_wizard_group1 = NULL;
    ui_dot4 = NULL;
    ui_line3 = NULL;
    ui_dot5 = NULL;
    ui_line4 = NULL;
    ui_dot6 = NULL;
    ui_content_group1 = NULL;
    ui_content_text_group1 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_label_calibration = NULL;
    ui_footer_group1 = NULL;
    ui_Button1 = NULL;

}
