// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_STEP3_H
#define UI_STEP3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_step3
extern void ui_step3_screen_init(void);
extern void ui_step3_screen_destroy(void);
extern void ui_event_step3(lv_event_t * e);
extern lv_obj_t * ui_step3;
extern lv_obj_t * ui_step3_bg;
extern lv_obj_t * ui_arrow;
extern lv_obj_t * ui_header_group2;
extern lv_obj_t * ui_wizard_group2;
extern lv_obj_t * ui_dot7;
extern lv_obj_t * ui_line5;
extern lv_obj_t * ui_dot8;
extern lv_obj_t * ui_line6;
extern lv_obj_t * ui_dot9;
extern lv_obj_t * ui_content_group2;
extern lv_obj_t * ui_content_text_group2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_footer_group2;
extern void ui_event_Button2_Button(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

