// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef UI_WELCOME_H
#define UI_WELCOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_welcome
extern void ui_welcome_screen_init(void);
extern void ui_welcome_screen_destroy(void);
extern void ui_event_welcome(lv_event_t * e);
extern lv_obj_t * ui_welcome;
extern lv_obj_t * ui_printer_in;
extern lv_obj_t * ui_header_group5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_content_group5;
extern lv_obj_t * ui_content_text_group3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_content_temp_group1;
extern lv_obj_t * ui_footer_group4;
extern void ui_event_Button3_Button(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

