// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#include "../ui.h"

// COMPONENT button menu

lv_obj_t * ui_button_menu_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_button_menu;
    cui_button_menu = lv_button_create(comp_parent);
    lv_obj_set_width(cui_button_menu, 293);
    lv_obj_set_height(cui_button_menu, 278);
    lv_obj_set_x(cui_button_menu, 0);
    lv_obj_set_y(cui_button_menu, -1);
    lv_obj_set_align(cui_button_menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_button_menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_button_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_button_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_button_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_button_menu, &ui_img_btn2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_button_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_button_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_button_menu, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_button_menu, &ui_img_btn2_press_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(cui_button_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(cui_button_menu, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_label_group;
    cui_label_group = lv_obj_create(cui_button_menu);
    lv_obj_set_width(cui_label_group, 144);
    lv_obj_set_height(cui_label_group, 111);
    lv_obj_set_x(cui_label_group, -30);
    lv_obj_set_y(cui_label_group, -31);
    lv_obj_set_align(cui_label_group, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(cui_label_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_label_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_label_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_label_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_label_group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_label_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_label_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_label_menu_button;
    cui_label_menu_button = lv_label_create(cui_label_group);
    lv_obj_set_width(cui_label_menu_button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label_menu_button, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label_menu_button, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label_menu_button, "Print");

    lv_obj_t * cui_icn_group;
    cui_icn_group = lv_obj_create(cui_button_menu);
    lv_obj_set_width(cui_icn_group, 80);
    lv_obj_set_height(cui_icn_group, 111);
    lv_obj_set_x(cui_icn_group, 27);
    lv_obj_set_y(cui_icn_group, -33);
    lv_obj_set_align(cui_icn_group, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(cui_icn_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_icn_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_icn_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_icn_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_icn_group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_icn_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_icn_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_icn_menu_button;
    cui_icn_menu_button = lv_image_create(cui_icn_group);
    lv_image_set_src(cui_icn_menu_button, &ui_img_icn_print_png);
    lv_obj_set_width(cui_icn_menu_button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_icn_menu_button, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_icn_menu_button, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_icn_menu_button, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_icn_menu_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_MENU_NUM);
    children[UI_COMP_BUTTON_MENU_BUTTON_MENU] = cui_button_menu;
    children[UI_COMP_BUTTON_MENU_LABEL_GROUP] = cui_label_group;
    children[UI_COMP_BUTTON_MENU_LABEL_GROUP_LABEL_MENU_BUTTON] = cui_label_menu_button;
    children[UI_COMP_BUTTON_MENU_ICN_GROUP] = cui_icn_group;
    children[UI_COMP_BUTTON_MENU_ICN_GROUP_ICN_MENU_BUTTON] = cui_icn_menu_button;
    lv_obj_add_event_cb(cui_button_menu, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_button_menu, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_button_menu_create_hook(cui_button_menu);
    return cui_button_menu;
}

