// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef _UI_COMP_BUTTON_H
#define _UI_COMP_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button
#define UI_COMP_BUTTON_BUTTON 0
#define UI_COMP_BUTTON_LABEL_BUTTON 1
#define _UI_COMP_BUTTON_NUM 2
lv_obj_t * ui_Button_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
