// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: 3d_Printer_2

#ifndef _3D_PRINTER_2_UI_H
#define _3D_PRINTER_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_welcome.h"
#include "screens/ui_step1.h"
#include "screens/ui_step2.h"
#include "screens/ui_step3.h"
#include "screens/ui_final.h"
#include "screens/ui_main_menu.h"
#include "screens/ui_printing.h"
#include "screens/ui_settings.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * topon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * topoff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * lefton_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * leftoff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opaon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opaoff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * arrow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * buttonon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * buttonoff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bed_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * printer_in_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_anim_printer_in_01_png);    // assets/anim/printer_in_01.png
LV_IMG_DECLARE(ui_img_btn1_png);    // assets/btn1.png
LV_IMG_DECLARE(ui_img_btn1_press_png);    // assets/btn1_press.png
LV_IMG_DECLARE(ui_img_ok_small_png);    // assets/ok_small.png
LV_IMG_DECLARE(ui_img_text_bg_left_png);    // assets/text_bg_left.png
LV_IMG_DECLARE(ui_img_text_bg_center_png);    // assets/text_bg_center.png
LV_IMG_DECLARE(ui_img_text_bg_right_png);    // assets/text_bg_right.png
LV_IMG_DECLARE(ui_img_separetor_png);    // assets/separetor.png
LV_IMG_DECLARE(ui_img_step2_bg_png);    // assets/step2_bg.png
LV_IMG_DECLARE(ui_img_bed_png);    // assets/bed.png
LV_IMG_DECLARE(ui_img_nozzle_png);    // assets/nozzle.png
LV_IMG_DECLARE(ui_img_step3_bg_png);    // assets/step3_bg.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_print_ready_png);    // assets/print_ready.png
LV_IMG_DECLARE(ui_img_ok_big_png);    // assets/ok_big.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_btn2_png);    // assets/btn2.png
LV_IMG_DECLARE(ui_img_btn2_press_png);    // assets/btn2_press.png
LV_IMG_DECLARE(ui_img_icn_print_png);    // assets/icn_print.png
LV_IMG_DECLARE(ui_img_icn_settings_png);    // assets/icn_settings.png
LV_IMG_DECLARE(ui_img_icn_control_png);    // assets/icn_control.png
LV_IMG_DECLARE(ui_img_separetor2_png);    // assets/separetor2.png
LV_IMG_DECLARE(ui_img_print_bar1_png);    // assets/print_bar1.png
LV_IMG_DECLARE(ui_img_print_bar2_png);    // assets/print_bar2.png
LV_IMG_DECLARE(ui_img_headtemp_png);    // assets/headtemp.png
LV_IMG_DECLARE(ui_img_bedtemp_png);    // assets/bedtemp.png
LV_IMG_DECLARE(ui_img_btn3_png);    // assets/btn3.png
LV_IMG_DECLARE(ui_img_btn3_press_png);    // assets/btn3_press.png
LV_IMG_DECLARE(ui_img_bg_settings_png);    // assets/bg_settings.png
LV_IMG_DECLARE(ui_img_icn_back_png);    // assets/icn_back.png
LV_IMG_DECLARE(ui_img_icn_move_png);    // assets/icn_move.png
LV_IMG_DECLARE(ui_img_icn_disable_png);    // assets/icn_disable.png
LV_IMG_DECLARE(ui_img_icn_home_png);    // assets/icn_home.png
LV_IMG_DECLARE(ui_img_icn_zoffset_png);    // assets/icn_zoffset.png
LV_IMG_DECLARE(ui_img_icn_filament_png);    // assets/icn_filament.png
LV_IMG_DECLARE(ui_img_anim_printer_in_02_png);    // assets/anim/printer_in_02.png
LV_IMG_DECLARE(ui_img_anim_printer_in_03_png);    // assets/anim/printer_in_03.png
LV_IMG_DECLARE(ui_img_anim_printer_in_04_png);    // assets/anim/printer_in_04.png
LV_IMG_DECLARE(ui_img_anim_printer_in_05_png);    // assets/anim/printer_in_05.png
LV_IMG_DECLARE(ui_img_anim_printer_in_06_png);    // assets/anim/printer_in_06.png
LV_IMG_DECLARE(ui_img_anim_printer_in_07_png);    // assets/anim/printer_in_07.png
LV_IMG_DECLARE(ui_img_anim_printer_in_08_png);    // assets/anim/printer_in_08.png
LV_IMG_DECLARE(ui_img_anim_printer_in_09_png);    // assets/anim/printer_in_09.png
LV_IMG_DECLARE(ui_img_anim_printer_in_10_png);    // assets/anim/printer_in_10.png
LV_IMG_DECLARE(ui_img_anim_printer_in_11_png);    // assets/anim/printer_in_11.png

// FONTS
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
